### ISSUE TITLE
eAPI password exposed in syslog

### ISSUE THREAD

**Issue by advornic** [arista-eosplus/ansible-eos#16]
From Mateusz:

"http://docs.ansible.com/intro_configuration.html#log-path
 
“This behavior is not on by default. Note that ansible will, without this setting, record module arguments called to the syslog of managed machines. Password arguments are excluded.“
 
This is potentially bad as you expose the password if the argument is anything different than “password”, so eapi_passwords are stored in syslog.
Even if you supply a log_path, the module arguments are still exposed in syslog."

**Comment by privateip** [comment]
This is fixed in the updated role refactor to 1.0 which implements http://github.com/arista-eosplus/pyeapi
