### ISSUE TITLE
Making a PR for Arista Modules into Ansible-Extras

### ISSUE THREAD

**Issue by nousdefions** [arista-eosplus/ansible-eos#20]
Hi, just wondering if you guys had plans to add your modules in `library/*` to the Ansible project. We would love to see a PR.

**Comment by privateip** [comment]
Hi @nousdefions 

@mpdehaan has been pretty adamant about keeping networking vendors libraries out of the core and extras repos and using Galaxy.  If this stance has changed, I'm more than happy to send over a PR with the latest modules as we are getting close to a pretty significant refresh of the library code.

**Comment by nousdefions** [comment]
Interesting. Wasn't aware. I am going to follow up on that internally and let you know either way.

Cheers

**Comment by nousdefions** [comment]
You were correct, apologies. Galaxy will become more vendor supportive in the near future.
