### ISSUE TITLE
SSH transport issues

### ISSUE THREAD

**Issue by advornic** [arista-eosplus/ansible-eos#25]
- "/usr/bin/LoadExtensions -f /tmp/pip_loader -d /persist/local/ansible/src" fails if the extension is already installed (need to ignore the failure or avoid attempting to install it)

Workaround for now is to use eapi connection, which is reliable.

**Comment by privateip** [comment]
Tagging this wontfix as the next revision of the eos role will not handle the bootstrap functions for the EOS node.  That functionality is going to move to a new role.  However, will keep this issue open to track until the new role is developed.

**Comment by privateip** [comment]
Loading of pyeapi is no longer included in the role... closing this issue.  For details on how to bootstrap the EOS please see http://ansible-eos.readthedocs.org/en/master/
