### ISSUE TITLE
Setting an interface back to default state

### ISSUE THREAD

**Issue by CullyB** [arista-eosplus/ansible-eos#27]
It would be nice to be able to set an interface back to its default state.  An example of how this would be useful would be if ansible is changing an interface from an edge port to an LACP group member.  In the example below, Ethernet15 and Ethernet16 were both edge ports, however Ethernet16 was set back to its default state prior to the eos_portchannel module being used and Ethernet15 was not

!
interface Ethernet15
   description Up by Ansible
   channel-group 130 mode active
   spanning-tree portfast
   no spanning-tree portfast auto
!
interface Ethernet16
   channel-group 130 mode active

**Comment by privateip** [comment]
PR closed #28
