### ISSUE TITLE
Quick question on http support

### ISSUE THREAD

**Issue by heathdbrown** [arista-eosplus/ansible-eos#29]
I believe I remember hearing that in the roadmap for this module there would be support to have the ability to hit the API directly from a remote server instead of ssh to the Arista and then doing a local http hit.

Is that still in the roadmap?

**Comment by advornic** [comment]
Yes, this is actually working in the development branch right now. Here are some instructions if you want to try it out:

1. Update Ansible role from source:
<pre>
cd /etc/ansible/roles
sudo rm arista*
sudo git clone http://github.com/arista-eosplus/ansible-eos arista.eos
</pre>
2. Install/update pyeapi
<pre>
sudo pip install pyeapi --upgrade
</pre>
3. Configure pyeapi
<pre>
cat ~/.eapi.conf (example)
</pre><pre>
[connection:Arista1]
username: admin
password: 
transport: https
...
</pre>

Add one section for each switch you want to control via Ansible.
Note: the username needs to be an EOS username (e.g. admin) and not one which you would created from bash, following the instructions on GitHub.

4. Enable eAPI on the switch if you haven't already done so.

5. Configure hosts file in Ansible
<pre>
/etc/ansible/hosts (example)
</pre><pre>
[arista]
Arista 1    
</pre>

6. Configure playbook 

7. Run playbook

8. Extra - if you want to get ping to work, configure the Ansible username in bash (as instructed on GitHub) and update your hosts file as follows:

<pre>
[arista]
Arista1 ansible_ssh_user=ansible
</pre>

Then it should work:
<pre>
$ ansible Arista1 -m ping
s7151 | success >> {
    "changed": false,
    "ping": "pong"
}
</pre>

Note that this is work in progress - feedback is welcome.

**Comment by heathdbrown** [comment]
Thanks I will take a look.
