### ISSUE TITLE
Username for ansible 

### ISSUE THREAD

**Issue by joozz** [arista-eosplus/ansible-eos#30]
Hi, 
for ansible beginners (like me) it can be helpful to to state that username of ansible on the ansible-server must be configured in the "hosts" file (ansible_ssh_user=ansible). Otherwise linux would just use its own name and the whole thing does not work. 
Thanks.

**Comment by privateip** [comment]
Thanks for the note, we are working to revamp the documentation and will be sure to clarify this point.

**Comment by privateip** [comment]
clarified in the latest v1.0.0 documentation found at http://ansible-eos.readthedocs.org/en/master/
