### ISSUE TITLE
Blank .eapi.conf file still required (if parameters moved to Ansible inventory/playbook)

### ISSUE THREAD

**Issue by ktbyers** [arista-eosplus/ansible-eos#32]
This struck me as a bit strange, but maybe it is the expected behavior:

Even after I moved all of my parameters from .eapi.conf to the Ansible inventory / playbook, I still was required to create a blank .eapi.conf file.

If I didn't have this blank .eapi.conf, I would get the following error (on Ansible playbook execution):

TASK: [Reset Ethernet3 description to default] ******************************** 
failed: [pynet-sw3] => {"failed": true}
msg: Connection name "localhost" not found

FATAL: all hosts have already failed -- aborting

Once I created a blank .eapi.conf file this error went away and the playbook would execute normally.

**Comment by privateip** [comment]
Thanks for filing this.  After researching it a bit, it is a bug in pyeapi and not the ansible eos modules.  I have opened https://github.com/arista-eosplus/pyeapi/issues/13 to track this bug and will close this issue.
