### ISSUE TITLE
trunk_allowed_vlans=all not idempotent

### ISSUE THREAD

**Issue by ktbyers** [arista-eosplus/ansible-eos#35]
If I run the following in a playbook multiple times, it will report it as "changed" even though nothing actually changes on the switch (i.e. the state is the same before and after).

    - name: Configure Ethernet3 to trunk
      eos_switchport: name=Ethernet3 mode=trunk trunk_native_vlan=1 trunk_allowed_vlans=all
        username={{username}}
        password={{password}}
        host={{host}}
        port={{port}}
        transport={{transport}}

If I remove "trunk_allowed_vlans=all", it works properly.

This is using ansible-eos 1.0.0 and pyeapi 0.3.0

Note, my Arista vEOS VM is old, but I doubt it matters.

**Comment by privateip** [comment]
Flagged this for being fixed in the next release however as a workaround, you should be able to use trunk_allowed_vlans=1-4094

**Comment by privateip** [comment]
We are going to leave the solution for this to setting the value to 1-4094 and not support the 'all' keyword at this time.
