### ISSUE TITLE
eapilib-0.3.0.tar.gz issues 

### ISSUE THREAD

**Issue by joozz** [arista-eosplus/ansible-eos#38]
Facing the following error message by the usage of eapilib-0.3.0.tar.gz using method A on the vEOS (execute scipts on the switch). The switch has no direct internet connection!  

Setup used: 
on vEOS: eapilib-0.3.0.tar.gz, vEOS 4.14.5F
on Ansible server: Python 2.7.6

1) netaddr was missing? Needed to install it manually on the switch via scp from ansible server 

  Running setup.py (path:/tmp/pip-Dx5Hfz-build/setup.py) egg_info for package from file:///tmp/v0.3.0.tar.gz
    Downloading/unpacking netaddr (from pyeapi==0.3.0)
  Cannot fetch index base URL https://pypi.python.org/simple/
  Could not find any downloads that satisfy the requirement netaddr (from pyeapi==0.3.0)
Cleaning up...
No distributions at all found for netaddr (from pyeapi==0.3.0)
Storing debug log for failure in /persist/local/ansible/.pip/pip.log
 
2) Following dependency (?) issues with item=eapilib-0.3.0.tar.gz

failed: [10.0.2.101] => (item=eapilib-0.3.0.tar.gz) => {"cmd": "/usr/bin/pip install --no-deps /persist/local/ansible/src/eapilib-0.3.0.tar.gz", "failed": true, "item": "eapilib-0.3.0.tar.gz"}
msg: stdout: Unpacking /persist/local/ansible/src/eapilib-0.3.0.tar.gz
Cleaning up...
Exception:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/site-packages/pip/commands/install.py", line 274, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/usr/lib/python2.7/site-packages/pip/req.py", line 1173, in prepare_files
    self.unpack_url(url, location, self.is_download)
  File "/usr/lib/python2.7/site-packages/pip/req.py", line 1316, in unpack_url
    return unpack_file_url(link, loc)
  File "/usr/lib/python2.7/site-packages/pip/download.py", line 356, in unpack_file_url
    unpack_file(source, location, content_type, link)
  File "/usr/lib/python2.7/site-packages/pip/util.py", line 625, in unpack_file
    untar_file(filename, location)
  File "/usr/lib/python2.7/site-packages/pip/util.py", line 543, in untar_file
    tar = tarfile.open(filename, mode)
  File "/usr/lib/python2.7/tarfile.py", line 1676, in open
    return func(name, filemode, fileobj, **kwargs)
  File "/usr/lib/python2.7/tarfile.py", line 1725, in gzopen
    **kwargs)
  File "/usr/lib/python2.7/tarfile.py", line 1703, in taropen
    return cls(name, mode, fileobj, **kwargs)
  File "/usr/lib/python2.7/tarfile.py", line 1572, in __init__
    self.firstmember = self.next()
  File "/usr/lib/python2.7/tarfile.py", line 2334, in next
    raise ReadError("empty file")
ReadError: empty file

Storing debug log for failure in /root/.pip/pip.log
FATAL: all hosts have already failed -- aborting

**Comment by privateip** [comment]
I'm not sure where its getting eapilib from?  That is a very old version of the role that is no longer developed or supported.  Did you install the role from source or from galaxy?   I would recommend removing any traces of that and make sure you are using the stable version (1.0.0) from Galaxy (https://galaxy.ansible.com/list#/roles/1359).  

Also, the following documentation resource will be helpful http://ansible-eos.readthedocs.org/en/v1.0.0/ for setting up your environment.

**Comment by phil-arista** [comment]
Is this okay to close? Any other issues related to this?

**Comment by phil-arista** [comment]
Closing this issue.  Please let us know if you hit this again with the current release.
