### ISSUE TITLE
Typo 4.1.1 eos_command

### ISSUE THREAD

**Issue by joozz** [arista-eosplus/ansible-eos#39]
is: 
- name: configure an interface
  eos_command: commands='interface Etherent1, no shutdown' mode=config

must be:
- name: configure an interface
  eos_command: commands='interface Ethernet1, no shutdown' mode=config

**Comment by phil-arista** [comment]
@joozz Sorry if I'm missing something but the 'is' and 'must be' are the same, no?

**Comment by joozz** [comment]
Hi Phil, there is a typo in the interface name: it must be  Ethernet1 not Etherent1.
