### ISSUE TITLE
I have been setting up Ansible for EOS and have my environment working such that I can send adhoc commands and receive output from my switches. However when I attempt to run a basic playbook to return the output of a show version I get an error returned that my connection profile in .eapi.conf is not found.

### ISSUE THREAD

**Issue by mprior1** [arista-eosplus/ansible-eos#40]
My playbook looks like this -
- name: Arista Ansible testing
  hosts: eossw02
  gather_facts: false

  roles:
   - role: arista.eos

  tasks:
   - name: Testing command (not idempotent)
     eos_command: commands="show version" connection={{ inventory_hostname }}
     register: show_version

My Ansible hosts file looks like this:
[eosswitches]

eossw01 ansible_ssh_host=10.102.126.3 ansible_ssh_user=ansible
eossw02 ansible_ssh_host=10.102.126.4 ansible_ssh_user=ansible

And my .eapi.conf file looks like this:

[connection:eossw01]
host: 10.102.126.3
username: eapi
password: password
enablepwd: password
transport: https

[connection:eossw02]
host: 10.102.126.4
username: eapi
password: password
enablepwd: password
transport: https

And the error looks like this:
failed: [eossw02] => {"failed": true}
msg: Connection name "eossw02" not found

FATAL: all hosts have already failed -- aborting

PLAY RECAP ********************************************************************
           to retry, use: --limit @/root/Aristatest.retry

eossw02                 : ok=0    changed=0    unreachable=0    failed=1

**Comment by phil-arista** [comment]
Hi @mprior1 - Is it your intent to run the modules locally on the Ansible Host and send eAPI calls to the switch, or do you want to use SSH to communicate with your nodes?
Ref: http://ansible-eos.readthedocs.org/en/develop/overview.html#the-ansible-eos-role

We just revamped the quickstart to clarify and simplify getting started:
Ref: http://ansible-eos.readthedocs.org/en/develop/quickstart.html

With your configuration above, you could quickly send eAPI calls to the switch by adding ``connection: local`` to your play:

```
- name: Arista Ansible testing
  hosts: eossw02
  gather_facts: false
  connection: local
 (rest of play)
```

**Comment by phil-arista** [comment]
Hello - just checking in to see if this is resolved and if we can close it.  Thanks!

**Comment by mprior1** [comment]
Hi Phil,

Yes you can thanks.  Apologies for not getting back to you sooner.

Regards

Mark Prior CCIE #9096
Infrastructure Architect
Consultancy Practice – Secure Networking

Computacenter (UK) Ltd

1 Thames Valley Park
Reading,
Berkshire RG6 1PT

T: 0118 935 6000
M: 07801 452764
Mobex: 452764

E: mark.prior@computacenter.com
W: www.computacenter.com


________________________________
