### ISSUE TITLE
msg: unsupported parameter for module: transport

### ISSUE THREAD

**Issue by RaviCharanReddy** [arista-eosplus/ansible-eos#70]
Hi,

I am trying to configure a EOS switch using ansible. I have established connection between them using SSH keys, and tested the connection. I wrote a simple playbook and trying to execute it. But I am getting a msg: unsupported parameter for module: transport

my playbook

---
- hosts: EOS
  gather_facts: no

  roles:
  - arista.eos

  tasks:
  - name: Configuring VLAN
    eos_vlan:
     vlanid=150
     name=NewVLAN
     transport={{ transport }}
     username={{ username }}
     password={{ password }}
     debug=yes
   register: vlan_cfg_output
 - debug: var=vlan_cfg_output

In my inventory file

[EOS]
Arista ansible_ssh_host=192.168.10.5

[EOS:vars]
ansible_ssh_user=ansible
transport=http
username=eapi
password=password

**Comment by phil-arista** [comment]
Hi @RaviCharanReddy 
Which versions of the following are you using?
Ansible,pyeapi, ansible-eos

I ran a test using SSH with your playbook and hosts file and it worked fine on one of my switches.

**Comment by RaviCharanReddy** [comment]
Hi Philip,

I am using Ansible 1.9.3, pyeapi - 0.3.3 and arista-eos latest version that
I downloaded Yesterday from ansible-galaxy.

I just started using ansible so I am not so proficient in it, how would I
check the arista-eos version ?

*Thanks & Regards,*
*RaviCharan*



On Tue, Oct 20, 2015 at 6:24 AM, Philip DiLeo <notifications@github.com>
wrote:

> Hi @RaviCharanReddy <https://github.com/RaviCharanReddy>
> Which versions of the following are you using?
> Ansible,pyeapi, ansible-eos
>
> I ran a test using SSH with your playbook and hosts file and it worked
> fine on one of my switches.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/arista-eosplus/ansible-eos/issues/70#issuecomment-149567408>
> .
>



-- 
Thanks & Regards,

RaviCharan
Masters - Network Communications
E-mail: *rrkallem@uh.edu <rrkallem@uh.edu>*
Contact: 832-914-3923

**Comment by RaviCharanReddy** [comment]
Philip, I am using Arista-eos role v1.1.0

**Comment by phil-arista** [comment]
Would you be able to send your playbook and hosts file to ansible-dev@arista.com? You really shouldn't hit this issue, which makes me think it's a formatting issue.  We can also get on a GoToMeeting to quickly sort it out.

**Comment by RaviCharanReddy** [comment]
Please find attached play-book and hosts file that I am using.

On Wed, Oct 21, 2015 at 2:26 PM, Philip DiLeo <notifications@github.com>
wrote:

> Would you be able to send your playbook and hosts file to
> ansible-dev@arista.com? You really shouldn't hit this issue, which makes
> me think it's a formatting issue. We can also get on a GoToMeeting to
> quickly sort it out.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/arista-eosplus/ansible-eos/issues/70#issuecomment-150028718>
> .
>



-- 
Thanks & Regards,

RaviCharan
Masters - Network Communications
E-mail: *rrkallem@uh.edu <rrkallem@uh.edu>*
Contact: 832-914-3923

**Comment by RaviCharanReddy** [comment]
Hi Philip,

I figured it out, there was some small mistake from my side. However, now I
am getting a new error.

[image: Inline image 1]



On Wed, Oct 21, 2015 at 2:26 PM, Philip DiLeo <notifications@github.com>
wrote:

> Would you be able to send your playbook and hosts file to
> ansible-dev@arista.com? You really shouldn't hit this issue, which makes
> me think it's a formatting issue. We can also get on a GoToMeeting to
> quickly sort it out.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/arista-eosplus/ansible-eos/issues/70#issuecomment-150028718>
> .
>



-- 
Thanks & Regards,

RaviCharan
Masters - Network Communications
E-mail: *rrkallem@uh.edu <rrkallem@uh.edu>*
Contact: 832-914-3923

**Comment by phil-arista** [comment]
Hi @RaviCharanReddy - did you get this all sorted out?

**Comment by RaviCharanReddy** [comment]
Hi Philip,
Yes my bad, it was a type error.
