### ISSUE TITLE
eos_command

### ISSUE THREAD

**Issue by jedelman8** [arista-eosplus/ansible-eos#72]
The description of this module states "The eos_command module provides a module for sending arbitray commands to the EOS node and returns the ouput.  Commands can  be either priviledged mode (enable) commands or configuration  commands." 

so it seems I should be able to send raw commands to make a change, but within the module, only `node.enable` is executed, and I believe for priv commands it should be `node.config()` - can you confirm this module support sending config commands?

```
def run_commands(module):
    commands = module.attributes['commands'].split(',')
    return module.node.enable(commands)
```

In addition, is it not possible to send a raw command that eAPI doesn't support JSON for?  I'm trying to send `show version | inc image` as a test and simply want plain text back.

**Comment by phil-arista** [comment]
This docstring needs updating.  eos_commands only supports enable commands now.  We also have a feature in PR #65, which will allow you to return the desired encoding scheme.

**Comment by phil-arista** [comment]
This should be closed, right?
