### ISSUE TITLE
domain_id parameter of eos_mlag_config module doesn't support '-' and dot

### ISSUE THREAD

**Issue by baswelman** [arista-eosplus/ansible-eos#90]
domain_id testing seem to truncate at the hyphen (and dot), so it always returns a changed.
value does get applied properly though.

changed: [sw01] => {"changed": true, "changes": {"domain_id": "dc.ams4_pod.2_rack.z2a.h01"}, "instance": {"domain_id": "dc", "local_interface": "Vlan4094", "peer_address": "10.x.y.z", "peer_link": "Port-Channel1000", "shutdown": false}}

Workaround is to use a underscore instead.

**Comment by phil-arista** [comment]
Thanks for this.  We'll take a look and get it fixed.

**Comment by grybak-arista** [comment]
This is a pyeapi issue, and is being addressed in arista-eosplus/pyeapi#91

**Comment by grybak-arista** [comment]
Fixed in pyeapi PR arista-eosplus/pyeapi#92
